### ISSUE TITLE
dxf转png字符不显示问题

### ISSUE THREAD

**Issue by ChvFily** [orcastor/addon-previewer#2]
dxf转png，在win上执行字符正常显示。
在linux  上不显示字符，不论是否执行-l /application/tempfile/common/fonts 字符编码，也是一样不显示。
./cad2x -o /application/tempfile/1730423818580.png /application/tempfile/1730423818580.dxf -ac -p 500x300 -m 2.0,2.0,2.0,2.0  -e ANSI_936 -f simsun -l /application/tempfile/common/fonts

./cad2x -o /application/tempfile/1730423818580.png /application/tempfile/1730423818580.dxf -ac -p 500x300 -m 2.0,2.0,2.0,2.0  -e ANSI_936 -f simsun

**Comment by ChvFily** [comment]
解决了。需要存在simsun.ttc（全小写，大小时修改名称就可以了）中文字符文件作为支撑。可以放在指定的目录如common/fonts下，从win系统上复制，如果为大写SIMSUN.TTC，可以修改为simsun.ttc。执行时：./cad2x -o /application/tempfile/1730423818580.png /application/tempfile/1730423818580.dxf -ac -p 500x300 -m 2.0,2.0,2.0,2.0 -e ANSI_936 -f simsun -l /application/tempfile/common/fonts

**Comment by orca-zhang** [comment]
对，linux下区分大小写，有的做法是创建一个软链接，我加到FAQ里，感谢。
